CREATE DATABASE yeticave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE yeticave;

CREATE TABLE categories(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(64) NOT NULL UNIQUE
);
 
CREATE TABLE lots(
	id INT AUTO_INCREMENT PRIMARY KEY,
	dtlot_add DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	lot_title CHAR(128) NOT NULL UNIQUE,
	description TEXT DEFAULT NULL,
	img_path CHAR(128) NOT NULL,
	cost_add INT NOT NULL,
	dt_end DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	step INT NOT NULL,
	category_id INT NOT NULL,
	user_id INT NOT NULL
);

CREATE TABLE bets(
	id INT AUTO_INCREMENT PRIMARY KEY,
	dtbet_add DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	cost_end INT NOT NULL,
	user_id INT NOT NULL,
	lot_id INT NOT NULL
);

CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt_reg DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	email CHAR(128) NOT NULL UNIQUE,
	name CHAR(64) NOT NULL UNIQUE,
	password CHAR (64) NOT NULL,
	avatar_path CHAR(128) NOT NULL,
	contacts CHAR(255) NOT NULL
);

CREATE UNIQUE INDEX catname ON categories(name);
CREATE UNIQUE INDEX title ON lots(lot_title);
CREATE UNIQUE INDEX mail ON users(email);
CREATE UNIQUE INDEX usrname ON users(name);
